#! /usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
    echo "Please run as root" >&2
    exit
fi

DEBUG_MODE=false
RESTIC_REPOSITORY=
RESTIC_ENV_FILE=
RESTIC_ARGS=()
RESTIC_ENV_VARS=()

while [ "$#" -gt 0 ]; do
    case $1 in
    -h|--host)
        case $2 in
        sora)
            RESTIC_REPOSITORY="rclone:b2:ggg-backups-sora";
            RESTIC_ENV_VARS+=("RESTIC_PASSWORD_FILE=@soraPasswordFile@");
            RESTIC_ENV_FILE="@soraEnvironmentFile@"
            ;;
        shiro)
            RESTIC_REPOSITORY="rclone:b2:ggg-backups-shiro";
            RESTIC_ENV_VARS+=("RESTIC_PASSWORD_FILE=@shiroPasswordFile@");
            RESTIC_ENV_FILE="@shiroEnvironmentFile@"
            ;;
        *)
            echo "Unknown host '$2'. Available hosts are: sora, shiro." >&2
            exit 2
            ;;
        esac;
        shift
        ;;
    -d|--debug) DEBUG_MODE=true; ;;
    --) shift; RESTIC_ARGS+=("$@"); break ;;
    "") ;;
    *) RESTIC_ARGS+=("$1") ;;
    esac
    shift
done

if [ -z "$RESTIC_REPOSITORY" ]; then
    echo "Please provide a host using --host." >&2
    exit 1
fi

if [ ! -f "$RESTIC_ENV_FILE" ]; then
    echo "The environment file does not exist." >&2
    exit 2
fi

RESTIC_ENV_VARS+=("RESTIC_REPOSITORY=$RESTIC_REPOSITORY");
RESTIC_ENV_VARS+=("RCLONE_CONFIG_B2_TYPE=b2");
RESTIC_ENV_VARS+=("RCLONE_CONFIG_B2_HARD_DELETE=true");
readarray -t ENV_FILE_VARS < "$RESTIC_ENV_FILE";
RESTIC_ENV_VARS+=("${ENV_FILE_VARS[@]}");

if [ "$DEBUG_MODE" = "true" ]; then
    echo "Env Vars:" >&2
    printf '  %s\n' "${RESTIC_ENV_VARS[@]}" >&2
    echo "Args:" >&2
    printf '  %s\n' "${RESTIC_ARGS[@]}" >&2
fi

env "${RESTIC_ENV_VARS[@]}" restic "${RESTIC_ARGS[@]}"