# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "@jesec/flood" = nodeEnv.buildNodePackage {
    name = "_at_jesec_slash_flood";
    packageName = "@jesec/flood";
    version = "0.0.0-master.6ff622c";
    src = fetchurl {
      url = "https://registry.npmjs.org/@jesec/flood/-/flood-0.0.0-master.6ff622c.tgz";
      sha512 = "yJ+S9ui/qgX5i0tChkXrXljSM4jLyf+IQtzQzkYE6MjAlv8HY5/XLQMBZMYcGBrx/54hV40unzz3D10OttCFlw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A modern Web UI for various torrent clients with multi-user and multi-client support";
      homepage = "https://github.com/jesec/flood#readme";
      license = "GPL-3.0-only";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
