# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2ce17ee3-d23e-44ab-8f7f-4d6a206d9b64";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" ];
    };

  boot.initrd.luks.devices."luks-2ce17ee3-d23e-44ab-8f7f-4d6a206d9b64".device = "/dev/disk/by-uuid/2ce17ee3-d23e-44ab-8f7f-4d6a206d9b64";
  boot.initrd.luks.devices."luks-2ce17ee3-d23e-44ab-8f7f-4d6a206d9b64".bypassWorkqueues = true;

  fileSystems."/home" =
    { device = "/dev/mapper/luks-2ce17ee3-d23e-44ab-8f7f-4d6a206d9b64";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3E77-1F76";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/608ccc5a-cf3c-4703-89af-05295b71c679"; randomEncryption = true; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
